name: Dist Windows

on:
  push:
    branches: [ master ]

jobs:

  dist-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Generate NSIS Windows dist files
        run: |
          npm install
          npm run dist
      - name: Upload Windows executable
        uses: actions/upload-artifact@v2
        with:
          name: Soletrando Setup 3.0.0.exe
          path: dist/Soletrando Setup 3.0.0.exe